version: 2
mergeable:
  - when: pull_request.opened
    name: 'Welcome'
    validate: []
    pass:
      - do: comment
        payload:
          body: >
            Welcome! :)
  - when: pull_request.*
    name: 'PR Title Convention'
    validate:
      - do: title
        must_include:
          regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test):\s.+\s\[[A-Z]+-[0-9]+\]$'
    pass:
      - do: checks
        status: 'success'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'Make sure this PR title follows convention.'
